import sympy
#from sympy_param import compile_gates, textbook_simp

clifford_decomps = {
    "I_q1": [('S', (0,)), ('Rz', -sympy.pi/2, (0,))],
    "I_q2": [('Z', (0,)), ('Rz', -sympy.pi, (0,))],
    "I_q3": [('Sdg', (0,)), ('Rz', -3*sympy.pi/2, (0,))],
    "I_q4": [('Rx', 2*sympy.pi, (0,))],
    "I_q5": [('S', (0,)), ('Rz', 3*sympy.pi/2, (0,))],
    "I_q6": [('Z', (0,)), ('Rz', sympy.pi, (0,))],
    "I_q7": [('Sdg', (0,)), ('Rz', sympy.pi/2, (0,))],
    "X_q1": [('U3', -sympy.pi, -3*sympy.pi/4, sympy.pi/4, (0,))],
    "X_q2": [('Rx', -sympy.pi, (0,))],
    "X_q3": [('U3', -sympy.pi, -sympy.pi/4, 3*sympy.pi/4, (0,))],
    "X_q4": [('U3', -sympy.pi, 0, sympy.pi, (0,))],
    "X_q5": [('U3', -sympy.pi, sympy.pi/4, -3*sympy.pi/4, (0,))],
    "X_q6": [('Rx', sympy.pi, (0,))],
    "X_q7": [('U3', -sympy.pi, 3*sympy.pi/4, -sympy.pi/4, (0,))],
    "Y_q1": [('U3', -sympy.pi, -sympy.pi/4, -sympy.pi/4, (0,))],
    "Y_q2": [('Ry', -sympy.pi, (0,))],
    "Y_q3": [('U3', -sympy.pi, sympy.pi/4, sympy.pi/4, (0,))],
    "Y_q4": [('U3', -sympy.pi, sympy.pi/2, sympy.pi/2, (0,))],
    "Y_q5": [('U3', -sympy.pi, 3*sympy.pi/4, 3*sympy.pi/4, (0,))],
    "Y_q6": [('Ry', sympy.pi, (0,))],
    "Y_q7": [('U3', -sympy.pi, -3*sympy.pi/4, -3*sympy.pi/4, (0,))],
    "Z_q1": [('Sdg', (0,)), ('Rz', -sympy.pi/2, (0,))],
    "Z_q2": [('Rz', -sympy.pi, (0,))],
    "Z_q3": [('S', (0,)), ('Rz', -3*sympy.pi/2, (0,))],
    "Z_q4": [('U3', 2*sympy.pi, 0, sympy.pi, (0,))],
    "Z_q5": [('Sdg', (0,)), ('Rz', 3*sympy.pi/2, (0,))],
    "Z_q6": [('Rz', sympy.pi, (0,))],
    "Z_q7": [('S', (0,)), ('Rz', sympy.pi/2, (0,))],
    "H_q1": [('Rx', -sympy.pi/2, (0,)), ('U2', sympy.pi/2, sympy.pi, (0,))],
    "H_q2": [('U2', sympy.pi, 0, (0,)), ('Y', (0,))],
    "H_q3": [('Rx', -3*sympy.pi/2, (0,)), ('U2', -sympy.pi/2, sympy.pi, (0,))],
    "H_q4": [('U3', -3*sympy.pi/2, 0, sympy.pi, (0,))],
    "H_q5": [('Rx', 3*sympy.pi/2, (0,)), ('U2', sympy.pi/2, sympy.pi, (0,))],
    "H_q6": [('Y', (0,)), ('U2', sympy.pi, 0, (0,))],
    "H_q7": [('Rx', sympy.pi/2, (0,)), ('U2', -sympy.pi/2, sympy.pi, (0,))],
    "HX": [('U2', 0, 0, (0,))],
    "HX_q1": [('Rx', sympy.pi/2, (0,)), ('U2', sympy.pi/2, 0, (0,))],
    "HX_q2": [('H', (0,)), ('Rx', -sympy.pi, (0,))],
    "HX_q3": [('Rx', 3*sympy.pi/2, (0,)), ('U2', -sympy.pi/2, 0, (0,))],
    "HX_q4": [('Ry', -3*sympy.pi/2, (0,))],
    "HX_q5": [('Rx', -3*sympy.pi/2, (0,)), ('U2', sympy.pi/2, 0, (0,))],
    "HX_q6": [('H', (0,)), ('Rx', sympy.pi, (0,))],
    "HX_q7": [('Rx', -sympy.pi/2, (0,)), ('U2', -sympy.pi/2, 0, (0,))],
    "HY": [('H', (0,)), ('Y', (0,))],
    "HY_q1": [('Rx', -sympy.pi/2, (0,)), ('U2', sympy.pi/2, 0, (0,))],
    "HY_q2": [('U2', sympy.pi, 0, (0,))],
    "HY_q3": [('Rx', sympy.pi/2, (0,)), ('U2', -sympy.pi/2, 0, (0,))],
    "HY_q4": [('Y', (0,)), ('H', (0,))],
    "HY_q5": [('Rx', 3*sympy.pi/2, (0,)), ('U2', sympy.pi/2, 0, (0,))],
    "HY_q6": [('U3', -3*sympy.pi/2, sympy.pi, 0, (0,))],
    "HY_q7": [('Rx', -3*sympy.pi/2, (0,)), ('U2', -sympy.pi/2, 0, (0,))],
    "HZ": [('U2', sympy.pi, sympy.pi, (0,))],
    "HZ_q1": [('Rx', -sympy.pi/2, (0,)), ('U2', -sympy.pi/2, sympy.pi, (0,))],
    "HZ_q2": [('Rx', -sympy.pi, (0,)), ('H', (0,))],
    "HZ_q3": [('Rx', -3*sympy.pi/2, (0,)), ('U2', sympy.pi/2, sympy.pi, (0,))],
    "HZ_q4": [('Ry', 3*sympy.pi/2, (0,))],
    "HZ_q5": [('Rx', 3*sympy.pi/2, (0,)), ('U2', -sympy.pi/2, sympy.pi, (0,))],
    "HZ_q6": [('Rx', sympy.pi, (0,)), ('H', (0,))],
    "HZ_q7": [('Rx', sympy.pi/2, (0,)), ('U2', sympy.pi/2, sympy.pi, (0,))],
    "S_q1": [('Z', (0,)), ('Rz', -sympy.pi/2, (0,))],
    "S_q2": [('Sdg', (0,)), ('Rz', -sympy.pi, (0,))],
    "S_q3": [('Rz', -3*sympy.pi/2, (0,))],
    "S_q4": [('U3', 2*sympy.pi, -sympy.pi/2, sympy.pi, (0,))],
    "S_q5": [('Rz', 3*sympy.pi/2, (0,)), ('Z', (0,))],
    "S_q6": [('Sdg', (0,)), ('Rz', sympy.pi, (0,))],
    "S_q7": [('Rz', sympy.pi/2, (0,))],
    "SX": [('U3', -sympy.pi, sympy.pi, sympy.pi/2, (0,))],
    "SX_q1": [('U3', -sympy.pi, -3*sympy.pi/4, 3*sympy.pi/4, (0,))],
    "SX_q2": [('U3', -sympy.pi, -sympy.pi/2, sympy.pi, (0,))],
    "SX_q3": [('U3', -sympy.pi, -sympy.pi/4, -3*sympy.pi/4, (0,))],
    "SX_q4": [('U3', -sympy.pi, 0, -sympy.pi/2, (0,))],
    "SX_q5": [('U3', -sympy.pi, sympy.pi/4, -sympy.pi/4, (0,))],
    "SX_q6": [('U3', -sympy.pi, sympy.pi/2, 0, (0,))],
    "SX_q7": [('U3', -sympy.pi, 3*sympy.pi/4, sympy.pi/4, (0,))],
    "SY": [('U3', -sympy.pi, -sympy.pi/2, 0, (0,))],
    "SY_q1": [('U3', -sympy.pi, -sympy.pi/4, sympy.pi/4, (0,))],
    "SY_q2": [('U3', -sympy.pi, 0, sympy.pi/2, (0,))],
    "SY_q3": [('U3', -sympy.pi, sympy.pi/4, 3*sympy.pi/4, (0,))],
    "SY_q4": [('U3', -sympy.pi, sympy.pi/2, sympy.pi, (0,))],
    "SY_q5": [('U3', -sympy.pi, 3*sympy.pi/4, -3*sympy.pi/4, (0,))],
    "SY_q6": [('U3', -sympy.pi, sympy.pi, -sympy.pi/2, (0,))],
    "SY_q7": [('U3', -sympy.pi, -3*sympy.pi/4, -sympy.pi/4, (0,))],
    "Sdg_q1": [('Rz', -sympy.pi/2, (0,))],
    "Sdg_q2": [('S', (0,)), ('Rz', -sympy.pi, (0,))],
    "Sdg_q3": [('Z', (0,)), ('Rz', -3*sympy.pi/2, (0,))],
    "Sdg_q4": [('U3', 2*sympy.pi, -sympy.pi/2, 0, (0,))],
    "Sdg_q5": [('Rz', 3*sympy.pi/2, (0,))],
    "Sdg_q6": [('S', (0,)), ('Rz', sympy.pi, (0,))],
    "Sdg_q7": [('Z', (0,)), ('Rz', sympy.pi/2, (0,))],
    "HS": [('U2', sympy.pi/2, sympy.pi, (0,))],
    "HS_q1": [('Rx', -sympy.pi/2, (0,)), ('U2', sympy.pi, sympy.pi, (0,))],
    "HS_q2": [('Rx', -sympy.pi, (0,)), ('U2', -sympy.pi/2, sympy.pi, (0,))],
    "HS_q3": [('Rx', -3*sympy.pi/2, (0,)), ('H', (0,))],
    "HS_q4": [('U3', -3*sympy.pi/2, sympy.pi/2, sympy.pi, (0,))],
    "HS_q5": [('Rx', 3*sympy.pi/2, (0,)), ('U2', sympy.pi, sympy.pi, (0,))],
    "HS_q6": [('U2', -sympy.pi/2, 0, (0,)), ('X', (0,))],
    "HS_q7": [('Sdg', (0,)), ('Sxdg', (0,))],
    "HSX": [('Sx', (0,)), ('U2', 0, 0, (0,))],
    "HSX_q1": [('Rx', 3*sympy.pi/2, (0,)), ('U2', sympy.pi, 0, (0,))],
    "HSX_q2": [('U3', -3*sympy.pi/2, -sympy.pi/2, 0, (0,))],
    "HSX_q3": [('Rx', -3*sympy.pi/2, (0,)), ('U2', 0, 0, (0,))],
    "HSX_q4": [('Sxdg', (0,)), ('U2', sympy.pi, 0, (0,))],
    "HSX_q5": [('Rx', -sympy.pi/2, (0,)), ('U2', sympy.pi, 0, (0,))],
    "HSX_q6": [('U2', -sympy.pi/2, 0, (0,))],
    "HSX_q7": [('Sdg', (0,)), ('Sx', (0,))],
    "HSY": [('U2', sympy.pi/2, 0, (0,))],
    "HSY_q1": [('Rx', sympy.pi/2, (0,)), ('U2', sympy.pi, 0, (0,))],
    "HSY_q2": [('Sx', (0,)), ('U2', sympy.pi, 0, (0,))],
    "HSY_q3": [('Rx', 3*sympy.pi/2, (0,)), ('U2', 0, 0, (0,))],
    "HSY_q4": [('U3', -3*sympy.pi/2, sympy.pi/2, 0, (0,))],
    "HSY_q5": [('Rx', -3*sympy.pi/2, (0,)), ('U2', sympy.pi, 0, (0,))],
    "HSY_q6": [('Sxdg', (0,)), ('U2', 0, 0, (0,))],
    "HSY_q7": [('S', (0,)), ('Sxdg', (0,))],
    "HSdg": [('U2', -sympy.pi/2, sympy.pi, (0,))],
    "HSdg_q1": [('S', (0,)), ('Sx', (0,))],
    "HSdg_q2": [('U2', sympy.pi/2, 0, (0,)), ('X', (0,))],
    "HSdg_q3": [('Rx', -3*sympy.pi/2, (0,)), ('U2', sympy.pi, sympy.pi, (0,))],
    "HSdg_q4": [('U3', -3*sympy.pi/2, -sympy.pi/2, sympy.pi, (0,))],
    "HSdg_q5": [('Rx', 3*sympy.pi/2, (0,)), ('H', (0,))],
    "HSdg_q6": [('Y', (0,)), ('U2', sympy.pi/2, 0, (0,))],
    "HSdg_q7": [('Rx', sympy.pi/2, (0,)), ('U2', sympy.pi, sympy.pi, (0,))],
    "SH": [('U2', 0, -sympy.pi/2, (0,))],
    "SH_q1": [('Rx', -sympy.pi/2, (0,)), ('Rz', -sympy.pi/2, (0,))],
    "SH_q2": [('U2', sympy.pi, sympy.pi/2, (0,)), ('Y', (0,))],
    "SH_q3": [('H', (0,)), ('Rx', -3*sympy.pi/2, (0,))],
    "SH_q4": [('U3', -3*sympy.pi/2, 0, -sympy.pi/2, (0,))],
    "SH_q5": [('Rx', 3*sympy.pi/2, (0,)), ('Rz', -sympy.pi/2, (0,))],
    "SH_q6": [('X', (0,)), ('U2', sympy.pi, sympy.pi/2, (0,))],
    "SH_q7": [('Sxdg', (0,)), ('Sdg', (0,))],
    "SHX": [('U2', 0, sympy.pi/2, (0,))],
    "SHX_q1": [('Sx', (0,)), ('S', (0,))],
    "SHX_q2": [('X', (0,)), ('U2', sympy.pi, -sympy.pi/2, (0,))],
    "SHX_q3": [('Rx', -3*sympy.pi/2, (0,)), ('Rz', sympy.pi/2, (0,))],
    "SHX_q4": [('U3', -3*sympy.pi/2, 0, sympy.pi/2, (0,))],
    "SHX_q5": [('H', (0,)), ('Rx', 3*sympy.pi/2, (0,))],
    "SHX_q6": [('Ry', sympy.pi, (0,)), ('U2', sympy.pi, sympy.pi/2, (0,))],
    "SHX_q7": [('Rx', sympy.pi/2, (0,)), ('Rz', sympy.pi/2, (0,))],
    "SHY": [('U2', sympy.pi, 0, (0,)), ('Sxdg', (0,))],
    "SHY_q1": [('Sxdg', (0,)), ('U3', -sympy.pi, 0, -sympy.pi/2, (0,))],
    "SHY_q2": [('U2', sympy.pi, sympy.pi/2, (0,))],
    "SHY_q3": [('Sx', (0,)), ('Sdg', (0,))],
    "SHY_q4": [('Sx', (0,)), ('Rz', -sympy.pi/2, (0,))],
    "SHY_q5": [('Sxdg', (0,)), ('U3', -sympy.pi, sympy.pi, sympy.pi/2, (0,))],
    "SHY_q6": [('U3', -3*sympy.pi/2, sympy.pi, sympy.pi/2, (0,))],
    "SHY_q7": [('Rx', -3*sympy.pi/2, (0,)), ('Rz', -sympy.pi/2, (0,))],
    "SHZ": [('U2', sympy.pi, -sympy.pi/2, (0,))],
    "SHZ_q1": [('Sx', (0,)), ('U3', -sympy.pi, 0, sympy.pi/2, (0,))],
    "SHZ_q2": [('U2', sympy.pi, 0, (0,)), ('Sx', (0,))],
    "SHZ_q3": [('Rx', 3*sympy.pi/2, (0,)), ('Rz', sympy.pi/2, (0,))],
    "SHZ_q4": [('U3', -3*sympy.pi/2, sympy.pi, -sympy.pi/2, (0,))],
    "SHZ_q5": [('Sx', (0,)), ('U3', -sympy.pi, sympy.pi, -sympy.pi/2, (0,))],
    "SHZ_q6": [('Sxdg', (0,)), ('Rz', sympy.pi/2, (0,))],
    "SHZ_q7": [('Sxdg', (0,)), ('S', (0,))],
    "Sx_q1": [('X', (0,)), ('Rx', -sympy.pi/2, (0,))],
    "Sx_q2": [('Rx', -sympy.pi, (0,)), ('Sxdg', (0,))],
    "Sx_q3": [('Rx', -3*sympy.pi/2, (0,))],
    "Sx_q4": [('Rx', 2*sympy.pi, (0,)), ('Sx', (0,))],
    "Sx_q5": [('X', (0,)), ('Rx', 3*sympy.pi/2, (0,))],
    "Sx_q6": [('Rx', sympy.pi, (0,)), ('Sxdg', (0,))],
    "Sx_q7": [('Rx', sympy.pi/2, (0,))],
    "Sxdg_q1": [('Rx', -sympy.pi/2, (0,))],
    "Sxdg_q2": [('Rx', -sympy.pi, (0,)), ('Sx', (0,))],
    "Sxdg_q3": [('X', (0,)), ('Rx', -3*sympy.pi/2, (0,))],
    "Sxdg_q4": [('Rx', 2*sympy.pi, (0,)), ('Sxdg', (0,))],
    "Sxdg_q5": [('Rx', 3*sympy.pi/2, (0,))],
    "Sxdg_q6": [('Rx', sympy.pi, (0,)), ('Sx', (0,))],
    "Sxdg_q7": [('X', (0,)), ('Rx', sympy.pi/2, (0,))],
    "SxY": [('Sx', (0,)), ('Y', (0,))],
    "SxY_q1": [('Ry', -sympy.pi, (0,)), ('Rx', -sympy.pi/2, (0,))],
    "SxY_q2": [('Sxdg', (0,)), ('Z', (0,))],
    "SxY_q3": [('U2', -sympy.pi/2, -sympy.pi/2, (0,))],
    "SxY_q4": [('Z', (0,)), ('Sx', (0,))],
    "SxY_q5": [('Ry', sympy.pi, (0,)), ('Rx', -sympy.pi/2, (0,))],
    "SxY_q6": [('Y', (0,)), ('Sxdg', (0,))],
    "SxY_q7": [('U3', -3*sympy.pi/2, -sympy.pi/2, -sympy.pi/2, (0,))],
    "SxZ": [('Y', (0,)), ('Sx', (0,))],
    "SxZ_q1": [('Ry', sympy.pi, (0,)), ('Rx', -3*sympy.pi/2, (0,))],
    "SxZ_q2": [('Ry', -sympy.pi, (0,)), ('Sx', (0,))],
    "SxZ_q3": [('U3', -3*sympy.pi/2, sympy.pi/2, sympy.pi/2, (0,))],
    "SxZ_q4": [('Sxdg', (0,)), ('Ry', sympy.pi, (0,))],
    "SxZ_q5": [('Ry', -sympy.pi, (0,)), ('Rx', -3*sympy.pi/2, (0,))],
    "SxZ_q6": [('Sxdg', (0,)), ('Y', (0,))],
    "SxZ_q7": [('U2', sympy.pi/2, sympy.pi/2, (0,))],
}

clifford_descs = {
    #Clifford additions at all global phases
    "I_q1": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*(sympy.I + 1)/2, 0], [0, sympy.sqrt(2)*(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "I_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.I, 0], [0, sympy.I]]).applyfunc(sympy.factor_terms)),
    "I_q3": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*(sympy.I - 1)/2, 0], [0, sympy.sqrt(2)*(sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "I_q4": (1, [], 
        lambda: sympy.Matrix([[-1, 0], [0, -1]]).applyfunc(sympy.factor_terms)),
    "I_q5": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*(sympy.I + 1)/2, 0], [0, -sympy.sqrt(2)*(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "I_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.I, 0], [0, -sympy.I]]).applyfunc(sympy.factor_terms)),
    "I_q7": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*(1 - sympy.I)/2, 0], [0, sympy.sqrt(2)*(1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "X_q1": (1, [], 
        lambda: sympy.Matrix([[0, sympy.sqrt(2)*(sympy.I + 1)/2], [sympy.sqrt(2)*(sympy.I + 1)/2, 0]]).applyfunc(sympy.factor_terms)),
    "X_q2": (1, [], 
        lambda: sympy.Matrix([[0, sympy.I], [sympy.I, 0]]).applyfunc(sympy.factor_terms)),
    "X_q3": (1, [], 
        lambda: sympy.Matrix([[0, sympy.sqrt(2)*(sympy.I - 1)/2], [sympy.sqrt(2)*(sympy.I - 1)/2, 0]]).applyfunc(sympy.factor_terms)),
    "X_q4": (1, [], 
        lambda: sympy.Matrix([[0, -1], [-1, 0]]).applyfunc(sympy.factor_terms)),
    "X_q5": (1, [], 
        lambda: sympy.Matrix([[0, -sympy.sqrt(2)*(sympy.I + 1)/2], [-sympy.sqrt(2)*(sympy.I + 1)/2, 0]]).applyfunc(sympy.factor_terms)),
    "X_q6": (1, [], 
        lambda: sympy.Matrix([[0, -sympy.I], [-sympy.I, 0]]).applyfunc(sympy.factor_terms)),
    "X_q7": (1, [], 
        lambda: sympy.Matrix([[0, sympy.sqrt(2)*(1 - sympy.I)/2], [sympy.sqrt(2)*(1 - sympy.I)/2, 0]]).applyfunc(sympy.factor_terms)),
    "Y_q1": (1, [], 
        lambda: sympy.Matrix([[0, sympy.sqrt(2)*(1 - sympy.I)/2], [sympy.sqrt(2)*(sympy.I - 1)/2, 0]]).applyfunc(sympy.factor_terms)),
    "Y_q2": (1, [], 
        lambda: sympy.Matrix([[0, 1], [-1, 0]]).applyfunc(sympy.factor_terms)),
    "Y_q3": (1, [], 
        lambda: sympy.Matrix([[0, sympy.sqrt(2)*(sympy.I + 1)/2], [-sympy.sqrt(2)*(sympy.I + 1)/2, 0]]).applyfunc(sympy.factor_terms)),
    "Y_q4": (1, [], 
        lambda: sympy.Matrix([[0, sympy.I], [-sympy.I, 0]]).applyfunc(sympy.factor_terms)),
    "Y_q5": (1, [], 
        lambda: sympy.Matrix([[0, sympy.sqrt(2)*(sympy.I - 1)/2], [sympy.sqrt(2)*(1 - sympy.I)/2, 0]]).applyfunc(sympy.factor_terms)),
    "Y_q6": (1, [], 
        lambda: sympy.Matrix([[0, -1], [1, 0]]).applyfunc(sympy.factor_terms)),
    "Y_q7": (1, [], 
        lambda: sympy.Matrix([[0, -sympy.sqrt(2)*(sympy.I + 1)/2], [sympy.sqrt(2)*(sympy.I + 1)/2, 0]]).applyfunc(sympy.factor_terms)),
    "Z_q1": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*(sympy.I + 1)/2, 0], [0, -sympy.sqrt(2)*(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "Z_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.I, 0], [0, -sympy.I]]).applyfunc(sympy.factor_terms)),
    "Z_q3": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*(sympy.I - 1)/2, 0], [0, sympy.sqrt(2)*(1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "Z_q4": (1, [], 
        lambda: sympy.Matrix([[-1, 0], [0, 1]]).applyfunc(sympy.factor_terms)),
    "Z_q5": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*(sympy.I + 1)/2, 0], [0, sympy.sqrt(2)*(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "Z_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.I, 0], [0, sympy.I]]).applyfunc(sympy.factor_terms)),
    "Z_q7": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*(1 - sympy.I)/2, 0], [0, sympy.sqrt(2)*(sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "H_q1": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, (sympy.I + 1)/2], [(sympy.I + 1)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "H_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "H_q3": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, (sympy.I - 1)/2], [(sympy.I - 1)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "H_q4": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, -sympy.sqrt(2)/2], [-sympy.sqrt(2)/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "H_q5": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, -(sympy.I + 1)/2], [-(sympy.I + 1)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "H_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "H_q7": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, (1 - sympy.I)/2], [(1 - sympy.I)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "HX": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, -sympy.sqrt(2)/2], [sympy.sqrt(2)/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "HX_q1": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, -(sympy.I + 1)/2], [(sympy.I + 1)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "HX_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "HX_q3": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, (1 - sympy.I)/2], [(sympy.I - 1)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "HX_q4": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, sympy.sqrt(2)/2], [-sympy.sqrt(2)/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "HX_q5": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, (sympy.I + 1)/2], [-(sympy.I + 1)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "HX_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "HX_q7": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, (sympy.I - 1)/2], [(1 - sympy.I)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "HY": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "HY_q1": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, (sympy.I - 1)/2], [(sympy.I - 1)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "HY_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, -sympy.sqrt(2)/2], [-sympy.sqrt(2)/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "HY_q3": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, -(sympy.I + 1)/2], [-(sympy.I + 1)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "HY_q4": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "HY_q5": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, (1 - sympy.I)/2], [(1 - sympy.I)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "HY_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, sympy.sqrt(2)/2], [sympy.sqrt(2)/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "HY_q7": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, (sympy.I + 1)/2], [(sympy.I + 1)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "HZ": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, sympy.sqrt(2)/2], [-sympy.sqrt(2)/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "HZ_q1": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, (sympy.I + 1)/2], [-(sympy.I + 1)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "HZ_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "HZ_q3": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, (sympy.I - 1)/2], [(1 - sympy.I)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "HZ_q4": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, -sympy.sqrt(2)/2], [sympy.sqrt(2)/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "HZ_q5": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, -(sympy.I + 1)/2], [(sympy.I + 1)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "HZ_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "HZ_q7": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, (1 - sympy.I)/2], [(sympy.I - 1)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "S_q1": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*(sympy.I + 1)/2, 0], [0, sympy.sqrt(2)*(sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "S_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.I, 0], [0, -1]]).applyfunc(sympy.factor_terms)),
    "S_q3": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*(sympy.I - 1)/2, 0], [0, -sympy.sqrt(2)*(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "S_q4": (1, [], 
        lambda: sympy.Matrix([[-1, 0], [0, -sympy.I]]).applyfunc(sympy.factor_terms)),
    "S_q5": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*(sympy.I + 1)/2, 0], [0, sympy.sqrt(2)*(1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "S_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.I, 0], [0, 1]]).applyfunc(sympy.factor_terms)),
    "S_q7": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*(1 - sympy.I)/2, 0], [0, sympy.sqrt(2)*(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "SX": (1, [], 
        lambda: sympy.Matrix([[0, sympy.I], [1, 0]]).applyfunc(sympy.factor_terms)),
    "SX_q1": (1, [], 
        lambda: sympy.Matrix([[0, sympy.sqrt(2)*(sympy.I - 1)/2], [sympy.sqrt(2)*(sympy.I + 1)/2, 0]]).applyfunc(sympy.factor_terms)),
    "SX_q2": (1, [], 
        lambda: sympy.Matrix([[0, -1], [sympy.I, 0]]).applyfunc(sympy.factor_terms)),
    "SX_q3": (1, [], 
        lambda: sympy.Matrix([[0, -sympy.sqrt(2)*(sympy.I + 1)/2], [sympy.sqrt(2)*(sympy.I - 1)/2, 0]]).applyfunc(sympy.factor_terms)),
    "SX_q4": (1, [], 
        lambda: sympy.Matrix([[0, -sympy.I], [-1, 0]]).applyfunc(sympy.factor_terms)),
    "SX_q5": (1, [], 
        lambda: sympy.Matrix([[0, sympy.sqrt(2)*(1 - sympy.I)/2], [-sympy.sqrt(2)*(sympy.I + 1)/2, 0]]).applyfunc(sympy.factor_terms)),
    "SX_q6": (1, [], 
        lambda: sympy.Matrix([[0, 1], [-sympy.I, 0]]).applyfunc(sympy.factor_terms)),
    "SX_q7": (1, [], 
        lambda: sympy.Matrix([[0, sympy.sqrt(2)*(sympy.I + 1)/2], [sympy.sqrt(2)*(1 - sympy.I)/2, 0]]).applyfunc(sympy.factor_terms)),
    "SY": (1, [], 
        lambda: sympy.Matrix([[0, 1], [sympy.I, 0]]).applyfunc(sympy.factor_terms)),
    "SY_q1": (1, [], 
        lambda: sympy.Matrix([[0, sympy.sqrt(2)*(sympy.I + 1)/2], [sympy.sqrt(2)*(sympy.I - 1)/2, 0]]).applyfunc(sympy.factor_terms)),
    "SY_q2": (1, [], 
        lambda: sympy.Matrix([[0, sympy.I], [-1, 0]]).applyfunc(sympy.factor_terms)),
    "SY_q3": (1, [], 
        lambda: sympy.Matrix([[0, sympy.sqrt(2)*(sympy.I - 1)/2], [-sympy.sqrt(2)*(sympy.I + 1)/2, 0]]).applyfunc(sympy.factor_terms)),
    "SY_q4": (1, [], 
        lambda: sympy.Matrix([[0, -1], [-sympy.I, 0]]).applyfunc(sympy.factor_terms)),
    "SY_q5": (1, [], 
        lambda: sympy.Matrix([[0, -sympy.sqrt(2)*(sympy.I + 1)/2], [sympy.sqrt(2)*(1 - sympy.I)/2, 0]]).applyfunc(sympy.factor_terms)),
    "SY_q6": (1, [], 
        lambda: sympy.Matrix([[0, -sympy.I], [1, 0]]).applyfunc(sympy.factor_terms)),
    "SY_q7": (1, [], 
        lambda: sympy.Matrix([[0, sympy.sqrt(2)*(1 - sympy.I)/2], [sympy.sqrt(2)*(sympy.I + 1)/2, 0]]).applyfunc(sympy.factor_terms)),
    "Sdg_q1": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*(sympy.I + 1)/2, 0], [0, sympy.sqrt(2)*(1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "Sdg_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.I, 0], [0, 1]]).applyfunc(sympy.factor_terms)),
    "Sdg_q3": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*(sympy.I - 1)/2, 0], [0, sympy.sqrt(2)*(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "Sdg_q4": (1, [], 
        lambda: sympy.Matrix([[-1, 0], [0, sympy.I]]).applyfunc(sympy.factor_terms)),
    "Sdg_q5": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*(sympy.I + 1)/2, 0], [0, sympy.sqrt(2)*(sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "Sdg_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.I, 0], [0, -1]]).applyfunc(sympy.factor_terms)),
    "Sdg_q7": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*(1 - sympy.I)/2, 0], [0, -sympy.sqrt(2)*(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "HS": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, sympy.sqrt(2)/2], [sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "HS_q1": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, (sympy.I + 1)/2], [(sympy.I - 1)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "HS_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "HS_q3": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, (sympy.I - 1)/2], [-(sympy.I + 1)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "HS_q4": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, -sympy.sqrt(2)/2], [-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "HS_q5": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, -(sympy.I + 1)/2], [(1 - sympy.I)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "HS_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "HS_q7": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, (1 - sympy.I)/2], [(sympy.I + 1)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "HSX": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "HSX_q1": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, (1 - sympy.I)/2], [(sympy.I + 1)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "HSX_q2": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, sympy.sqrt(2)/2], [sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "HSX_q3": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, (sympy.I + 1)/2], [(sympy.I - 1)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "HSX_q4": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "HSX_q5": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, (sympy.I - 1)/2], [-(sympy.I + 1)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "HSX_q6": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, -sympy.sqrt(2)/2], [-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "HSX_q7": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, -(sympy.I + 1)/2], [(1 - sympy.I)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "HSY": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, -sympy.sqrt(2)/2], [sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "HSY_q1": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, -(sympy.I + 1)/2], [(sympy.I - 1)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "HSY_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "HSY_q3": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, (1 - sympy.I)/2], [-(sympy.I + 1)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "HSY_q4": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, sympy.sqrt(2)/2], [-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "HSY_q5": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, (sympy.I + 1)/2], [(1 - sympy.I)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "HSY_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "HSY_q7": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, (sympy.I - 1)/2], [(sympy.I + 1)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "HSdg": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, sympy.sqrt(2)/2], [-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "HSdg_q1": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, (sympy.I + 1)/2], [(1 - sympy.I)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "HSdg_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "HSdg_q3": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, (sympy.I - 1)/2], [(sympy.I + 1)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "HSdg_q4": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, -sympy.sqrt(2)/2], [sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "HSdg_q5": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, -(sympy.I + 1)/2], [(sympy.I - 1)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "HSdg_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "HSdg_q7": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, (1 - sympy.I)/2], [-(sympy.I + 1)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "SH": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "SH_q1": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, (sympy.I - 1)/2], [(sympy.I + 1)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "SH_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2], [sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "SH_q3": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, -(sympy.I + 1)/2], [(sympy.I - 1)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "SH_q4": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "SH_q5": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, (1 - sympy.I)/2], [-(sympy.I + 1)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "SH_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2], [-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "SH_q7": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, (sympy.I + 1)/2], [(1 - sympy.I)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "SHX": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "SHX_q1": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, (1 - sympy.I)/2], [(sympy.I + 1)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "SHX_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2], [sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "SHX_q3": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, (sympy.I + 1)/2], [(sympy.I - 1)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "SHX_q4": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "SHX_q5": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, (sympy.I - 1)/2], [-(sympy.I + 1)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "SHX_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2], [-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "SHX_q7": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, -(sympy.I + 1)/2], [(1 - sympy.I)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "SHY": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2], [sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "SHY_q1": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, -(sympy.I + 1)/2], [(sympy.I - 1)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "SHY_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "SHY_q3": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, (1 - sympy.I)/2], [-(sympy.I + 1)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "SHY_q4": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2], [-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "SHY_q5": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, (sympy.I + 1)/2], [(1 - sympy.I)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "SHY_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "SHY_q7": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, (sympy.I - 1)/2], [(sympy.I + 1)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "SHZ": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "SHZ_q1": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, (sympy.I - 1)/2], [-(sympy.I + 1)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "SHZ_q2": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2], [-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "SHZ_q3": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, -(sympy.I + 1)/2], [(1 - sympy.I)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "SHZ_q4": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "SHZ_q5": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, (1 - sympy.I)/2], [(sympy.I + 1)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "SHZ_q6": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2], [sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "SHZ_q7": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, (sympy.I + 1)/2], [(sympy.I - 1)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "Sx_q1": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2], [sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "Sx_q2": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, (sympy.I + 1)/2], [(sympy.I + 1)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "Sx_q3": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "Sx_q4": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, (sympy.I - 1)/2], [(sympy.I - 1)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "Sx_q5": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2], [-sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "Sx_q6": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, -(sympy.I + 1)/2], [-(sympy.I + 1)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "Sx_q7": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "Sxdg_q1": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "Sxdg_q2": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, (sympy.I - 1)/2], [(sympy.I - 1)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "Sxdg_q3": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2], [-sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "Sxdg_q4": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, -(sympy.I + 1)/2], [-(sympy.I + 1)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "Sxdg_q5": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "Sxdg_q6": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, (1 - sympy.I)/2], [(1 - sympy.I)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "Sxdg_q7": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2], [sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "SxY": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, (1 - sympy.I)/2], [(sympy.I - 1)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "SxY_q1": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2], [-sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "SxY_q2": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, (sympy.I + 1)/2], [-(sympy.I + 1)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "SxY_q3": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "SxY_q4": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, (sympy.I - 1)/2], [(1 - sympy.I)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "SxY_q5": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2], [sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "SxY_q6": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, -(sympy.I + 1)/2], [(sympy.I + 1)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "SxY_q7": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "SxZ": (1, [], 
        lambda: sympy.Matrix([[(sympy.I + 1)/2, (1 - sympy.I)/2], [(sympy.I - 1)/2, -(sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "SxZ_q1": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2], [-sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "SxZ_q2": (1, [], 
        lambda: sympy.Matrix([[(sympy.I - 1)/2, (sympy.I + 1)/2], [-(sympy.I + 1)/2, (1 - sympy.I)/2]]).applyfunc(sympy.factor_terms)),
    "SxZ_q3": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2], [-sympy.sqrt(2)*sympy.I/2, sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
    "SxZ_q4": (1, [], 
        lambda: sympy.Matrix([[-(sympy.I + 1)/2, (sympy.I - 1)/2], [(1 - sympy.I)/2, (sympy.I + 1)/2]]).applyfunc(sympy.factor_terms)),
    "SxZ_q5": (1, [], 
        lambda: sympy.Matrix([[-sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2], [sympy.sqrt(2)/2, sympy.sqrt(2)*sympy.I/2]]).applyfunc(sympy.factor_terms)),
    "SxZ_q6": (1, [], 
        lambda: sympy.Matrix([[(1 - sympy.I)/2, -(sympy.I + 1)/2], [(sympy.I + 1)/2, (sympy.I - 1)/2]]).applyfunc(sympy.factor_terms)),
    "SxZ_q7": (1, [], 
        lambda: sympy.Matrix([[sympy.sqrt(2)/2, -sympy.sqrt(2)*sympy.I/2], [sympy.sqrt(2)*sympy.I/2, -sympy.sqrt(2)/2]]).applyfunc(sympy.factor_terms)),
}

gate_inverses_clifford = (
    ('I', 'I'), ('I_q1', 'I_q7'), ('I_q2', 'I_q6'), ('I_q3', 'I_q5'), ('I_q4', 'I_q4'), ('I_q5', 'I_q3'), ('I_q6', 'I_q2'), ('I_q7', 'I_q1'), 
    ('X', 'X'), ('X_q1', 'X_q7'), ('X_q2', 'X_q6'), ('X_q3', 'X_q5'), ('X_q4', 'X_q4'), ('X_q5', 'X_q3'), ('X_q6', 'X_q2'), ('X_q7', 'X_q1'), 
    ('Y', 'Y'), ('Y_q1', 'Y_q7'), ('Y_q2', 'Y_q6'), ('Y_q3', 'Y_q5'), ('Y_q4', 'Y_q4'), ('Y_q5', 'Y_q3'), ('Y_q6', 'Y_q2'), ('Y_q7', 'Y_q1'), 
    ('Z', 'Z'), ('Z_q1', 'Z_q7'), ('Z_q2', 'Z_q6'), ('Z_q3', 'Z_q5'), ('Z_q4', 'Z_q4'), ('Z_q5', 'Z_q3'), ('Z_q6', 'Z_q2'), ('Z_q7', 'Z_q1'), 
    ('H', 'H'), ('H_q1', 'H_q7'), ('H_q2', 'H_q6'), ('H_q3', 'H_q5'), ('H_q4', 'H_q4'), ('H_q5', 'H_q3'), ('H_q6', 'H_q2'), ('H_q7', 'H_q1'), 
    ('HX', 'HZ'), ('HX_q1', 'HZ_q7'), ('HX_q2', 'HZ_q6'), ('HX_q3', 'HZ_q5'), ('HX_q4', 'HZ_q4'), ('HX_q5', 'HZ_q3'), ('HX_q6', 'HZ_q2'), ('HX_q7', 'HZ_q1'), 
    ('HY', 'HY_q4'), ('HY_q1', 'HY_q3'), ('HY_q2', 'HY_q2'), ('HY_q3', 'HY_q1'), ('HY_q4', 'HY'), ('HY_q5', 'HY_q7'), ('HY_q6', 'HY_q6'), ('HY_q7', 'HY_q5'), 
    ('HZ', 'HX'), ('HZ_q1', 'HX_q7'), ('HZ_q2', 'HX_q6'), ('HZ_q3', 'HX_q5'), ('HZ_q4', 'HX_q4'), ('HZ_q5', 'HX_q3'), ('HZ_q6', 'HX_q2'), ('HZ_q7', 'HX_q1'), 
    ('S', 'Sdg'), ('S_q1', 'Sdg_q7'), ('S_q2', 'Sdg_q6'), ('S_q3', 'Sdg_q5'), ('S_q4', 'Sdg_q4'), ('S_q5', 'Sdg_q3'), ('S_q6', 'Sdg_q2'), ('S_q7', 'Sdg_q1'), 
    ('SX', 'SX_q6'), ('SX_q1', 'SX_q5'), ('SX_q2', 'SX_q4'), ('SX_q3', 'SX_q3'), ('SX_q4', 'SX_q2'), ('SX_q5', 'SX_q1'), ('SX_q6', 'SX'), ('SX_q7', 'SX_q7'), 
    ('SY', 'SY_q6'), ('SY_q1', 'SY_q5'), ('SY_q2', 'SY_q4'), ('SY_q3', 'SY_q3'), ('SY_q4', 'SY_q2'), ('SY_q5', 'SY_q1'), ('SY_q6', 'SY'), ('SY_q7', 'SY_q7'), 
    ('Sdg', 'S'), ('Sdg_q1', 'S_q7'), ('Sdg_q2', 'S_q6'), ('Sdg_q3', 'S_q5'), ('Sdg_q4', 'S_q4'), ('Sdg_q5', 'S_q3'), ('Sdg_q6', 'S_q2'), ('Sdg_q7', 'S_q1'), 
    ('HS', 'SHX'), ('HS_q1', 'SHX_q7'), ('HS_q2', 'SHX_q6'), ('HS_q3', 'SHX_q5'), ('HS_q4', 'SHX_q4'), ('HS_q5', 'SHX_q3'), ('HS_q6', 'SHX_q2'), ('HS_q7', 'SHX_q1'), 
    ('HSX', 'SHZ_q6'), ('HSX_q1', 'SHZ_q5'), ('HSX_q2', 'SHZ_q4'), ('HSX_q3', 'SHZ_q3'), ('HSX_q4', 'SHZ_q2'), ('HSX_q5', 'SHZ_q1'), ('HSX_q6', 'SHZ'), ('HSX_q7', 'SHZ_q7'), 
    ('HSY', 'SHY_q2'), ('HSY_q1', 'SHY_q1'), ('HSY_q2', 'SHY'), ('HSY_q3', 'SHY_q7'), ('HSY_q4', 'SHY_q6'), ('HSY_q5', 'SHY_q5'), ('HSY_q6', 'SHY_q4'), ('HSY_q7', 'SHY_q3'), 
    ('HSdg', 'SH'), ('HSdg_q1', 'SH_q7'), ('HSdg_q2', 'SH_q6'), ('HSdg_q3', 'SH_q5'), ('HSdg_q4', 'SH_q4'), ('HSdg_q5', 'SH_q3'), ('HSdg_q6', 'SH_q2'), ('HSdg_q7', 'SH_q1'), 
    ('SH', 'HSdg'), ('SH_q1', 'HSdg_q7'), ('SH_q2', 'HSdg_q6'), ('SH_q3', 'HSdg_q5'), ('SH_q4', 'HSdg_q4'), ('SH_q5', 'HSdg_q3'), ('SH_q6', 'HSdg_q2'), ('SH_q7', 'HSdg_q1'), 
    ('SHX', 'HS'), ('SHX_q1', 'HS_q7'), ('SHX_q2', 'HS_q6'), ('SHX_q3', 'HS_q5'), ('SHX_q4', 'HS_q4'), ('SHX_q5', 'HS_q3'), ('SHX_q6', 'HS_q2'), ('SHX_q7', 'HS_q1'), 
    ('SHY', 'HSY_q2'), ('SHY_q1', 'HSY_q1'), ('SHY_q2', 'HSY'), ('SHY_q3', 'HSY_q7'), ('SHY_q4', 'HSY_q6'), ('SHY_q5', 'HSY_q5'), ('SHY_q6', 'HSY_q4'), ('SHY_q7', 'HSY_q3'), 
    ('SHZ', 'HSX_q6'), ('SHZ_q1', 'HSX_q5'), ('SHZ_q2', 'HSX_q4'), ('SHZ_q3', 'HSX_q3'), ('SHZ_q4', 'HSX_q2'), ('SHZ_q5', 'HSX_q1'), ('SHZ_q6', 'HSX'), ('SHZ_q7', 'HSX_q7'), 
    ('Sx', 'Sxdg'), ('Sx_q1', 'Sxdg_q7'), ('Sx_q2', 'Sxdg_q6'), ('Sx_q3', 'Sxdg_q5'), ('Sx_q4', 'Sxdg_q4'), ('Sx_q5', 'Sxdg_q3'), ('Sx_q6', 'Sxdg_q2'), ('Sx_q7', 'Sxdg_q1'), 
    ('Sxdg', 'Sx'), ('Sxdg_q1', 'Sx_q7'), ('Sxdg_q2', 'Sx_q6'), ('Sxdg_q3', 'Sx_q5'), ('Sxdg_q4', 'Sx_q4'), ('Sxdg_q5', 'Sx_q3'), ('Sxdg_q6', 'Sx_q2'), ('Sxdg_q7', 'Sx_q1'), 
    ('SxY', 'SxY_q6'), ('SxY_q1', 'SxY_q5'), ('SxY_q2', 'SxY_q4'), ('SxY_q3', 'SxY_q3'), ('SxY_q4', 'SxY_q2'), ('SxY_q5', 'SxY_q1'), ('SxY_q6', 'SxY'), ('SxY_q7', 'SxY_q7'), 
    ('SxZ', 'SxZ_q6'), ('SxZ_q1', 'SxZ_q5'), ('SxZ_q2', 'SxZ_q4'), ('SxZ_q3', 'SxZ_q3'), ('SxZ_q4', 'SxZ_q2'), ('SxZ_q5', 'SxZ_q1'), ('SxZ_q6', 'SxZ'), ('SxZ_q7', 'SxZ_q7'),
)

aliases = {
    "I": (('P', (0,)), ('Rx', (0,)), ('Ry', (0,)), ('Rz', (0,)), ('U3', (0, -3*sympy.pi/4, 3*sympy.pi/4,)), ('U3', (0, -sympy.pi/2, sympy.pi/2,)), ('U3', (0, -sympy.pi/4, sympy.pi/4,)), ('U3', (0, 0, 0,)), ('U3', (0, sympy.pi/4, -sympy.pi/4,)), ('U3', (0, sympy.pi/2, -sympy.pi/2,)), ('U3', (0, 3*sympy.pi/4, -3*sympy.pi/4,)), ('U3', (0, sympy.pi, sympy.pi,)),),
    "I_q4": (('Rx', (2*sympy.pi,)), ('Ry', (2*sympy.pi,)), ('Rz', (2*sympy.pi,)), ('U3', (2*sympy.pi, -3*sympy.pi/4, 3*sympy.pi/4,)), ('U3', (2*sympy.pi, -sympy.pi/2, sympy.pi/2,)), ('U3', (2*sympy.pi, -sympy.pi/4, sympy.pi/4,)), ('U3', (2*sympy.pi, 0, 0,)), ('U3', (2*sympy.pi, sympy.pi/4, -sympy.pi/4,)), ('U3', (2*sympy.pi, sympy.pi/2, -sympy.pi/2,)), ('U3', (2*sympy.pi, 3*sympy.pi/4, -3*sympy.pi/4,)), ('U3', (2*sympy.pi, sympy.pi, sympy.pi,)),),
    "X": (('U3', (-sympy.pi, sympy.pi, 0,)), ('U3', (sympy.pi, 0, sympy.pi,)),),
    "X_q1": (('U3', (-sympy.pi, -3*sympy.pi/4, sympy.pi/4,)), ('U3', (sympy.pi, sympy.pi/4, -3*sympy.pi/4,)),),
    "X_q2": (('Rx', (-sympy.pi,)), ('U3', (-sympy.pi, -sympy.pi/2, sympy.pi/2,)), ('U3', (sympy.pi, sympy.pi/2, -sympy.pi/2,)),),
    "X_q3": (('U3', (-sympy.pi, -sympy.pi/4, 3*sympy.pi/4,)), ('U3', (sympy.pi, 3*sympy.pi/4, -sympy.pi/4,)),),
    "X_q4": (('U3', (-sympy.pi, 0, sympy.pi,)), ('U3', (sympy.pi, sympy.pi, 0,)),),
    "X_q5": (('U3', (-sympy.pi, sympy.pi/4, -3*sympy.pi/4,)), ('U3', (sympy.pi, -3*sympy.pi/4, sympy.pi/4,)),),
    "X_q6": (('Rx', (sympy.pi,)), ('U3', (-sympy.pi, sympy.pi/2, -sympy.pi/2,)), ('U3', (sympy.pi, -sympy.pi/2, sympy.pi/2,)),),
    "X_q7": (('U3', (-sympy.pi, 3*sympy.pi/4, -sympy.pi/4,)), ('U3', (sympy.pi, -sympy.pi/4, 3*sympy.pi/4,)),),
    "Y": (('U3', (-sympy.pi, -sympy.pi/2, -sympy.pi/2,)), ('U3', (sympy.pi, sympy.pi/2, sympy.pi/2,)),),
    "Y_q1": (('U3', (-sympy.pi, -sympy.pi/4, -sympy.pi/4,)), ('U3', (sympy.pi, 3*sympy.pi/4, 3*sympy.pi/4,)),),
    "Y_q2": (('Ry', (-sympy.pi,)), ('U3', (-sympy.pi, 0, 0,)), ('U3', (sympy.pi, sympy.pi, sympy.pi,)),),
    "Y_q3": (('U3', (-sympy.pi, sympy.pi/4, sympy.pi/4,)), ('U3', (sympy.pi, -3*sympy.pi/4, -3*sympy.pi/4,)),),
    "Y_q4": (('U3', (-sympy.pi, sympy.pi/2, sympy.pi/2,)), ('U3', (sympy.pi, -sympy.pi/2, -sympy.pi/2,)),),
    "Y_q5": (('U3', (-sympy.pi, 3*sympy.pi/4, 3*sympy.pi/4,)), ('U3', (sympy.pi, -sympy.pi/4, -sympy.pi/4,)),),
    "Y_q6": (('Ry', (sympy.pi,)), ('U3', (-sympy.pi, sympy.pi, sympy.pi,)), ('U3', (sympy.pi, 0, 0,)),),
    "Y_q7": (('U3', (-sympy.pi, -3*sympy.pi/4, -3*sympy.pi/4,)), ('U3', (sympy.pi, sympy.pi/4, sympy.pi/4,)),),
    "Z": (('P', (sympy.pi,)), ('U3', (0, -3*sympy.pi/4, -sympy.pi/4,)), ('U3', (0, -sympy.pi/2, -sympy.pi/2,)), ('U3', (0, -sympy.pi/4, -3*sympy.pi/4,)), ('U3', (0, 0, sympy.pi,)), ('U3', (0, sympy.pi/4, 3*sympy.pi/4,)), ('U3', (0, sympy.pi/2, sympy.pi/2,)), ('U3', (0, 3*sympy.pi/4, sympy.pi/4,)), ('U3', (0, sympy.pi, 0,)),),
    "Z_q2": (('Rz', (-sympy.pi,)),),
    "Z_q4": (('U3', (2*sympy.pi, -3*sympy.pi/4, -sympy.pi/4,)), ('U3', (2*sympy.pi, -sympy.pi/2, -sympy.pi/2,)), ('U3', (2*sympy.pi, -sympy.pi/4, -3*sympy.pi/4,)), ('U3', (2*sympy.pi, 0, sympy.pi,)), ('U3', (2*sympy.pi, sympy.pi/4, 3*sympy.pi/4,)), ('U3', (2*sympy.pi, sympy.pi/2, sympy.pi/2,)), ('U3', (2*sympy.pi, 3*sympy.pi/4, sympy.pi/4,)), ('U3', (2*sympy.pi, sympy.pi, 0,)),),
    "Z_q6": (('Rz', (sympy.pi,)),),
    "H": (('U2', (0, sympy.pi,)), ('U3', (-sympy.pi/2, sympy.pi, 0,)), ('U3', (sympy.pi/2, 0, sympy.pi,)),),
    "H_q4": (('U3', (-3*sympy.pi/2, 0, sympy.pi,)), ('U3', (3*sympy.pi/2, sympy.pi, 0,)),),
    "HX": (('Ry', (sympy.pi/2,)), ('U2', (0, 0,)), ('U3', (-sympy.pi/2, sympy.pi, sympy.pi,)), ('U3', (sympy.pi/2, 0, 0,)),),
    "HX_q4": (('Ry', (-3*sympy.pi/2,)), ('U3', (-3*sympy.pi/2, 0, 0,)), ('U3', (3*sympy.pi/2, sympy.pi, sympy.pi,)),),
    "HY_q2": (('U2', (sympy.pi, 0,)), ('U3', (-sympy.pi/2, 0, sympy.pi,)), ('U3', (sympy.pi/2, sympy.pi, 0,)),),
    "HY_q6": (('U3', (-3*sympy.pi/2, sympy.pi, 0,)), ('U3', (3*sympy.pi/2, 0, sympy.pi,)),),
    "HZ": (('Ry', (-sympy.pi/2,)), ('U2', (sympy.pi, sympy.pi,)), ('U3', (-sympy.pi/2, 0, 0,)), ('U3', (sympy.pi/2, sympy.pi, sympy.pi,)),),
    "HZ_q4": (('Ry', (3*sympy.pi/2,)), ('U3', (-3*sympy.pi/2, sympy.pi, sympy.pi,)), ('U3', (3*sympy.pi/2, 0, 0,)),),
    "S": (('P', (sympy.pi/2,)), ('U3', (0, -3*sympy.pi/4, -3*sympy.pi/4,)), ('U3', (0, -sympy.pi/2, sympy.pi,)), ('U3', (0, -sympy.pi/4, 3*sympy.pi/4,)), ('U3', (0, 0, sympy.pi/2,)), ('U3', (0, sympy.pi/4, sympy.pi/4,)), ('U3', (0, sympy.pi/2, 0,)), ('U3', (0, 3*sympy.pi/4, -sympy.pi/4,)), ('U3', (0, sympy.pi, -sympy.pi/2,)),),
    "S_q3": (('Rz', (-3*sympy.pi/2,)),),
    "S_q4": (('U3', (2*sympy.pi, -3*sympy.pi/4, -3*sympy.pi/4,)), ('U3', (2*sympy.pi, -sympy.pi/2, sympy.pi,)), ('U3', (2*sympy.pi, -sympy.pi/4, 3*sympy.pi/4,)), ('U3', (2*sympy.pi, 0, sympy.pi/2,)), ('U3', (2*sympy.pi, sympy.pi/4, sympy.pi/4,)), ('U3', (2*sympy.pi, sympy.pi/2, 0,)), ('U3', (2*sympy.pi, 3*sympy.pi/4, -sympy.pi/4,)), ('U3', (2*sympy.pi, sympy.pi, -sympy.pi/2,)),),
    "S_q7": (('Rz', (sympy.pi/2,)),),
    "SX": (('U3', (-sympy.pi, sympy.pi, sympy.pi/2,)), ('U3', (sympy.pi, 0, -sympy.pi/2,)),),
    "SX_q1": (('U3', (-sympy.pi, -3*sympy.pi/4, 3*sympy.pi/4,)), ('U3', (sympy.pi, sympy.pi/4, -sympy.pi/4,)),),
    "SX_q2": (('U3', (-sympy.pi, -sympy.pi/2, sympy.pi,)), ('U3', (sympy.pi, sympy.pi/2, 0,)),),
    "SX_q3": (('U3', (-sympy.pi, -sympy.pi/4, -3*sympy.pi/4,)), ('U3', (sympy.pi, 3*sympy.pi/4, sympy.pi/4,)),),
    "SX_q4": (('U3', (-sympy.pi, 0, -sympy.pi/2,)), ('U3', (sympy.pi, sympy.pi, sympy.pi/2,)),),
    "SX_q5": (('U3', (-sympy.pi, sympy.pi/4, -sympy.pi/4,)), ('U3', (sympy.pi, -3*sympy.pi/4, 3*sympy.pi/4,)),),
    "SX_q6": (('U3', (-sympy.pi, sympy.pi/2, 0,)), ('U3', (sympy.pi, -sympy.pi/2, sympy.pi,)),),
    "SX_q7": (('U3', (-sympy.pi, 3*sympy.pi/4, sympy.pi/4,)), ('U3', (sympy.pi, -sympy.pi/4, -3*sympy.pi/4,)),),
    "SY": (('U3', (-sympy.pi, -sympy.pi/2, 0,)), ('U3', (sympy.pi, sympy.pi/2, sympy.pi,)),),
    "SY_q1": (('U3', (-sympy.pi, -sympy.pi/4, sympy.pi/4,)), ('U3', (sympy.pi, 3*sympy.pi/4, -3*sympy.pi/4,)),),
    "SY_q2": (('U3', (-sympy.pi, 0, sympy.pi/2,)), ('U3', (sympy.pi, sympy.pi, -sympy.pi/2,)),),
    "SY_q3": (('U3', (-sympy.pi, sympy.pi/4, 3*sympy.pi/4,)), ('U3', (sympy.pi, -3*sympy.pi/4, -sympy.pi/4,)),),
    "SY_q4": (('U3', (-sympy.pi, sympy.pi/2, sympy.pi,)), ('U3', (sympy.pi, -sympy.pi/2, 0,)),),
    "SY_q5": (('U3', (-sympy.pi, 3*sympy.pi/4, -3*sympy.pi/4,)), ('U3', (sympy.pi, -sympy.pi/4, sympy.pi/4,)),),
    "SY_q6": (('U3', (-sympy.pi, sympy.pi, -sympy.pi/2,)), ('U3', (sympy.pi, 0, sympy.pi/2,)),),
    "SY_q7": (('U3', (-sympy.pi, -3*sympy.pi/4, -sympy.pi/4,)), ('U3', (sympy.pi, sympy.pi/4, 3*sympy.pi/4,)),),
    "Sdg": (('P', (-sympy.pi/2,)), ('U3', (0, -3*sympy.pi/4, sympy.pi/4,)), ('U3', (0, -sympy.pi/2, 0,)), ('U3', (0, -sympy.pi/4, -sympy.pi/4,)), ('U3', (0, 0, -sympy.pi/2,)), ('U3', (0, sympy.pi/4, -3*sympy.pi/4,)), ('U3', (0, sympy.pi/2, sympy.pi,)), ('U3', (0, 3*sympy.pi/4, 3*sympy.pi/4,)), ('U3', (0, sympy.pi, sympy.pi/2,)),),
    "Sdg_q1": (('Rz', (-sympy.pi/2,)),),
    "Sdg_q4": (('U3', (2*sympy.pi, -3*sympy.pi/4, sympy.pi/4,)), ('U3', (2*sympy.pi, -sympy.pi/2, 0,)), ('U3', (2*sympy.pi, -sympy.pi/4, -sympy.pi/4,)), ('U3', (2*sympy.pi, 0, -sympy.pi/2,)), ('U3', (2*sympy.pi, sympy.pi/4, -3*sympy.pi/4,)), ('U3', (2*sympy.pi, sympy.pi/2, sympy.pi,)), ('U3', (2*sympy.pi, 3*sympy.pi/4, 3*sympy.pi/4,)), ('U3', (2*sympy.pi, sympy.pi, sympy.pi/2,)),),
    "Sdg_q5": (('Rz', (3*sympy.pi/2,)),),
    "HS": (('U2', (sympy.pi/2, sympy.pi,)), ('U3', (-sympy.pi/2, -sympy.pi/2, 0,)), ('U3', (sympy.pi/2, sympy.pi/2, sympy.pi,)),),
    "HS_q4": (('U3', (-3*sympy.pi/2, sympy.pi/2, sympy.pi,)), ('U3', (3*sympy.pi/2, -sympy.pi/2, 0,)),),
    "HSX_q2": (('U3', (-3*sympy.pi/2, -sympy.pi/2, 0,)), ('U3', (3*sympy.pi/2, sympy.pi/2, sympy.pi,)),),
    "HSX_q6": (('U2', (-sympy.pi/2, 0,)), ('U3', (-sympy.pi/2, sympy.pi/2, sympy.pi,)), ('U3', (sympy.pi/2, -sympy.pi/2, 0,)),),
    "HSY": (('U2', (sympy.pi/2, 0,)), ('U3', (-sympy.pi/2, -sympy.pi/2, sympy.pi,)), ('U3', (sympy.pi/2, sympy.pi/2, 0,)),),
    "HSY_q4": (('U3', (-3*sympy.pi/2, sympy.pi/2, 0,)), ('U3', (3*sympy.pi/2, -sympy.pi/2, sympy.pi,)),),
    "HSdg": (('U2', (-sympy.pi/2, sympy.pi,)), ('U3', (-sympy.pi/2, sympy.pi/2, 0,)), ('U3', (sympy.pi/2, -sympy.pi/2, sympy.pi,)),),
    "HSdg_q4": (('U3', (-3*sympy.pi/2, -sympy.pi/2, sympy.pi,)), ('U3', (3*sympy.pi/2, sympy.pi/2, 0,)),),
    "SH": (('U2', (0, -sympy.pi/2,)), ('U3', (-sympy.pi/2, sympy.pi, sympy.pi/2,)), ('U3', (sympy.pi/2, 0, -sympy.pi/2,)),),
    "SH_q4": (('U3', (-3*sympy.pi/2, 0, -sympy.pi/2,)), ('U3', (3*sympy.pi/2, sympy.pi, sympy.pi/2,)),),
    "SHX": (('U2', (0, sympy.pi/2,)), ('U3', (-sympy.pi/2, sympy.pi, -sympy.pi/2,)), ('U3', (sympy.pi/2, 0, sympy.pi/2,)),),
    "SHX_q4": (('U3', (-3*sympy.pi/2, 0, sympy.pi/2,)), ('U3', (3*sympy.pi/2, sympy.pi, -sympy.pi/2,)),),
    "SHY_q2": (('U2', (sympy.pi, sympy.pi/2,)), ('U3', (-sympy.pi/2, 0, -sympy.pi/2,)), ('U3', (sympy.pi/2, sympy.pi, sympy.pi/2,)),),
    "SHY_q6": (('U3', (-3*sympy.pi/2, sympy.pi, sympy.pi/2,)), ('U3', (3*sympy.pi/2, 0, -sympy.pi/2,)),),
    "SHZ": (('U2', (sympy.pi, -sympy.pi/2,)), ('U3', (-sympy.pi/2, 0, sympy.pi/2,)), ('U3', (sympy.pi/2, sympy.pi, -sympy.pi/2,)),),
    "SHZ_q4": (('U3', (-3*sympy.pi/2, sympy.pi, -sympy.pi/2,)), ('U3', (3*sympy.pi/2, 0, sympy.pi/2,)),),
    "Sx_q3": (('Rx', (-3*sympy.pi/2,)), ('U3', (-3*sympy.pi/2, -sympy.pi/2, sympy.pi/2,)), ('U3', (3*sympy.pi/2, sympy.pi/2, -sympy.pi/2,)),),
    "Sx_q7": (('Rx', (sympy.pi/2,)), ('U2', (-sympy.pi/2, sympy.pi/2,)), ('U3', (-sympy.pi/2, sympy.pi/2, -sympy.pi/2,)), ('U3', (sympy.pi/2, -sympy.pi/2, sympy.pi/2,)),),
    "Sxdg_q1": (('Rx', (-sympy.pi/2,)), ('U2', (sympy.pi/2, -sympy.pi/2,)), ('U3', (-sympy.pi/2, -sympy.pi/2, sympy.pi/2,)), ('U3', (sympy.pi/2, sympy.pi/2, -sympy.pi/2,)),),
    "Sxdg_q5": (('Rx', (3*sympy.pi/2,)), ('U3', (-3*sympy.pi/2, sympy.pi/2, -sympy.pi/2,)), ('U3', (3*sympy.pi/2, -sympy.pi/2, sympy.pi/2,)),),
    "SxY_q3": (('U2', (-sympy.pi/2, -sympy.pi/2,)), ('U3', (-sympy.pi/2, sympy.pi/2, sympy.pi/2,)), ('U3', (sympy.pi/2, -sympy.pi/2, -sympy.pi/2,)),),
    "SxY_q7": (('U3', (-3*sympy.pi/2, -sympy.pi/2, -sympy.pi/2,)), ('U3', (3*sympy.pi/2, sympy.pi/2, sympy.pi/2,)),),
    "SxZ_q3": (('U3', (-3*sympy.pi/2, sympy.pi/2, sympy.pi/2,)), ('U3', (3*sympy.pi/2, -sympy.pi/2, -sympy.pi/2,)),),
    "SxZ_q7": (('U2', (sympy.pi/2, sympy.pi/2,)), ('U3', (-sympy.pi/2, -sympy.pi/2, -sympy.pi/2,)), ('U3', (sympy.pi/2, sympy.pi/2, sympy.pi/2,)),),
    "T": (('P', (sympy.pi/4,)), ('U3', (0, -3*sympy.pi/4, sympy.pi,)), ('U3', (0, -sympy.pi/2, 3*sympy.pi/4,)), ('U3', (0, -sympy.pi/4, sympy.pi/2,)), ('U3', (0, 0, sympy.pi/4,)), ('U3', (0, sympy.pi/4, 0,)), ('U3', (0, sympy.pi/2, -sympy.pi/4,)), ('U3', (0, 3*sympy.pi/4, -sympy.pi/2,)), ('U3', (0, sympy.pi, -3*sympy.pi/4,)),),
    "Tdg": (('P', (-sympy.pi/4,)), ('U3', (0, -3*sympy.pi/4, sympy.pi/2,)), ('U3', (0, -sympy.pi/2, sympy.pi/4,)), ('U3', (0, -sympy.pi/4, 0,)), ('U3', (0, 0, -sympy.pi/4,)), ('U3', (0, sympy.pi/4, -sympy.pi/2,)), ('U3', (0, sympy.pi/2, -3*sympy.pi/4,)), ('U3', (0, 3*sympy.pi/4, sympy.pi,)), ('U3', (0, sympy.pi, 3*sympy.pi/4,)),),
    "P_m6": (('P', (-3*sympy.pi/4,)), ('U3', (0, -3*sympy.pi/4, 0,)), ('U3', (0, -sympy.pi/2, -sympy.pi/4,)), ('U3', (0, -sympy.pi/4, -sympy.pi/2,)), ('U3', (0, 0, -3*sympy.pi/4,)), ('U3', (0, sympy.pi/4, sympy.pi,)), ('U3', (0, sympy.pi/2, 3*sympy.pi/4,)), ('U3', (0, 3*sympy.pi/4, sympy.pi/2,)), ('U3', (0, sympy.pi, sympy.pi/4,)),),
    "P_6": (('P', (3*sympy.pi/4,)), ('U3', (0, -3*sympy.pi/4, -sympy.pi/2,)), ('U3', (0, -sympy.pi/2, -3*sympy.pi/4,)), ('U3', (0, -sympy.pi/4, sympy.pi,)), ('U3', (0, 0, 3*sympy.pi/4,)), ('U3', (0, sympy.pi/4, sympy.pi/2,)), ('U3', (0, sympy.pi/2, sympy.pi/4,)), ('U3', (0, 3*sympy.pi/4, 0,)), ('U3', (0, sympy.pi, -sympy.pi/4,)),),
    "U2_m6_m6": (('U2', (-3*sympy.pi/4, -3*sympy.pi/4,)), ('U3', (-sympy.pi/2, sympy.pi/4, sympy.pi/4,)), ('U3', (sympy.pi/2, -3*sympy.pi/4, -3*sympy.pi/4,)),),
    "U2_m6_m4": (('U2', (-3*sympy.pi/4, -sympy.pi/2,)), ('U3', (-sympy.pi/2, sympy.pi/4, sympy.pi/2,)), ('U3', (sympy.pi/2, -3*sympy.pi/4, -sympy.pi/2,)),),
    "U2_m6_m2": (('U2', (-3*sympy.pi/4, -sympy.pi/4,)), ('U3', (-sympy.pi/2, sympy.pi/4, 3*sympy.pi/4,)), ('U3', (sympy.pi/2, -3*sympy.pi/4, -sympy.pi/4,)),),
    "U2_m6_0": (('U2', (-3*sympy.pi/4, 0,)), ('U3', (-sympy.pi/2, sympy.pi/4, sympy.pi,)), ('U3', (sympy.pi/2, -3*sympy.pi/4, 0,)),),
    "U2_m6_2": (('U2', (-3*sympy.pi/4, sympy.pi/4,)), ('U3', (-sympy.pi/2, sympy.pi/4, -3*sympy.pi/4,)), ('U3', (sympy.pi/2, -3*sympy.pi/4, sympy.pi/4,)),),
    "U2_m6_4": (('U2', (-3*sympy.pi/4, sympy.pi/2,)), ('U3', (-sympy.pi/2, sympy.pi/4, -sympy.pi/2,)), ('U3', (sympy.pi/2, -3*sympy.pi/4, sympy.pi/2,)),),
    "U2_m6_6": (('U2', (-3*sympy.pi/4, 3*sympy.pi/4,)), ('U3', (-sympy.pi/2, sympy.pi/4, -sympy.pi/4,)), ('U3', (sympy.pi/2, -3*sympy.pi/4, 3*sympy.pi/4,)),),
    "U2_m6_8": (('U2', (-3*sympy.pi/4, sympy.pi,)), ('U3', (-sympy.pi/2, sympy.pi/4, 0,)), ('U3', (sympy.pi/2, -3*sympy.pi/4, sympy.pi,)),),
    "U2_m4_m6": (('U2', (-sympy.pi/2, -3*sympy.pi/4,)), ('U3', (-sympy.pi/2, sympy.pi/2, sympy.pi/4,)), ('U3', (sympy.pi/2, -sympy.pi/2, -3*sympy.pi/4,)),),
    "U2_m4_m2": (('U2', (-sympy.pi/2, -sympy.pi/4,)), ('U3', (-sympy.pi/2, sympy.pi/2, 3*sympy.pi/4,)), ('U3', (sympy.pi/2, -sympy.pi/2, -sympy.pi/4,)),),
    "U2_m4_2": (('U2', (-sympy.pi/2, sympy.pi/4,)), ('U3', (-sympy.pi/2, sympy.pi/2, -3*sympy.pi/4,)), ('U3', (sympy.pi/2, -sympy.pi/2, sympy.pi/4,)),),
    "U2_m4_6": (('U2', (-sympy.pi/2, 3*sympy.pi/4,)), ('U3', (-sympy.pi/2, sympy.pi/2, -sympy.pi/4,)), ('U3', (sympy.pi/2, -sympy.pi/2, 3*sympy.pi/4,)),),
    "U2_m2_m6": (('U2', (-sympy.pi/4, -3*sympy.pi/4,)), ('U3', (-sympy.pi/2, 3*sympy.pi/4, sympy.pi/4,)), ('U3', (sympy.pi/2, -sympy.pi/4, -3*sympy.pi/4,)),),
    "U2_m2_m4": (('U2', (-sympy.pi/4, -sympy.pi/2,)), ('U3', (-sympy.pi/2, 3*sympy.pi/4, sympy.pi/2,)), ('U3', (sympy.pi/2, -sympy.pi/4, -sympy.pi/2,)),),
    "U2_m2_m2": (('U2', (-sympy.pi/4, -sympy.pi/4,)), ('U3', (-sympy.pi/2, 3*sympy.pi/4, 3*sympy.pi/4,)), ('U3', (sympy.pi/2, -sympy.pi/4, -sympy.pi/4,)),),
    "U2_m2_0": (('U2', (-sympy.pi/4, 0,)), ('U3', (-sympy.pi/2, 3*sympy.pi/4, sympy.pi,)), ('U3', (sympy.pi/2, -sympy.pi/4, 0,)),),
    "U2_m2_2": (('U2', (-sympy.pi/4, sympy.pi/4,)), ('U3', (-sympy.pi/2, 3*sympy.pi/4, -3*sympy.pi/4,)), ('U3', (sympy.pi/2, -sympy.pi/4, sympy.pi/4,)),),
    "U2_m2_4": (('U2', (-sympy.pi/4, sympy.pi/2,)), ('U3', (-sympy.pi/2, 3*sympy.pi/4, -sympy.pi/2,)), ('U3', (sympy.pi/2, -sympy.pi/4, sympy.pi/2,)),),
    "U2_m2_6": (('U2', (-sympy.pi/4, 3*sympy.pi/4,)), ('U3', (-sympy.pi/2, 3*sympy.pi/4, -sympy.pi/4,)), ('U3', (sympy.pi/2, -sympy.pi/4, 3*sympy.pi/4,)),),
    "U2_m2_8": (('U2', (-sympy.pi/4, sympy.pi,)), ('U3', (-sympy.pi/2, 3*sympy.pi/4, 0,)), ('U3', (sympy.pi/2, -sympy.pi/4, sympy.pi,)),),
    "U2_0_m6": (('U2', (0, -3*sympy.pi/4,)), ('U3', (-sympy.pi/2, sympy.pi, sympy.pi/4,)), ('U3', (sympy.pi/2, 0, -3*sympy.pi/4,)),),
    "U2_0_m2": (('U2', (0, -sympy.pi/4,)), ('U3', (-sympy.pi/2, sympy.pi, 3*sympy.pi/4,)), ('U3', (sympy.pi/2, 0, -sympy.pi/4,)),),
    "U2_0_2": (('U2', (0, sympy.pi/4,)), ('U3', (-sympy.pi/2, sympy.pi, -3*sympy.pi/4,)), ('U3', (sympy.pi/2, 0, sympy.pi/4,)),),
    "U2_0_6": (('U2', (0, 3*sympy.pi/4,)), ('U3', (-sympy.pi/2, sympy.pi, -sympy.pi/4,)), ('U3', (sympy.pi/2, 0, 3*sympy.pi/4,)),),
    "U2_2_m6": (('U2', (sympy.pi/4, -3*sympy.pi/4,)), ('U3', (-sympy.pi/2, -3*sympy.pi/4, sympy.pi/4,)), ('U3', (sympy.pi/2, sympy.pi/4, -3*sympy.pi/4,)),),
    "U2_2_m4": (('U2', (sympy.pi/4, -sympy.pi/2,)), ('U3', (-sympy.pi/2, -3*sympy.pi/4, sympy.pi/2,)), ('U3', (sympy.pi/2, sympy.pi/4, -sympy.pi/2,)),),
    "U2_2_m2": (('U2', (sympy.pi/4, -sympy.pi/4,)), ('U3', (-sympy.pi/2, -3*sympy.pi/4, 3*sympy.pi/4,)), ('U3', (sympy.pi/2, sympy.pi/4, -sympy.pi/4,)),),
    "U2_2_0": (('U2', (sympy.pi/4, 0,)), ('U3', (-sympy.pi/2, -3*sympy.pi/4, sympy.pi,)), ('U3', (sympy.pi/2, sympy.pi/4, 0,)),),
    "U2_2_2": (('U2', (sympy.pi/4, sympy.pi/4,)), ('U3', (-sympy.pi/2, -3*sympy.pi/4, -3*sympy.pi/4,)), ('U3', (sympy.pi/2, sympy.pi/4, sympy.pi/4,)),),
    "U2_2_4": (('U2', (sympy.pi/4, sympy.pi/2,)), ('U3', (-sympy.pi/2, -3*sympy.pi/4, -sympy.pi/2,)), ('U3', (sympy.pi/2, sympy.pi/4, sympy.pi/2,)),),
    "U2_2_6": (('U2', (sympy.pi/4, 3*sympy.pi/4,)), ('U3', (-sympy.pi/2, -3*sympy.pi/4, -sympy.pi/4,)), ('U3', (sympy.pi/2, sympy.pi/4, 3*sympy.pi/4,)),),
    "U2_2_8": (('U2', (sympy.pi/4, sympy.pi,)), ('U3', (-sympy.pi/2, -3*sympy.pi/4, 0,)), ('U3', (sympy.pi/2, sympy.pi/4, sympy.pi,)),),
    "U2_4_m6": (('U2', (sympy.pi/2, -3*sympy.pi/4,)), ('U3', (-sympy.pi/2, -sympy.pi/2, sympy.pi/4,)), ('U3', (sympy.pi/2, sympy.pi/2, -3*sympy.pi/4,)),),
    "U2_4_m2": (('U2', (sympy.pi/2, -sympy.pi/4,)), ('U3', (-sympy.pi/2, -sympy.pi/2, 3*sympy.pi/4,)), ('U3', (sympy.pi/2, sympy.pi/2, -sympy.pi/4,)),),
    "U2_4_2": (('U2', (sympy.pi/2, sympy.pi/4,)), ('U3', (-sympy.pi/2, -sympy.pi/2, -3*sympy.pi/4,)), ('U3', (sympy.pi/2, sympy.pi/2, sympy.pi/4,)),),
    "U2_4_6": (('U2', (sympy.pi/2, 3*sympy.pi/4,)), ('U3', (-sympy.pi/2, -sympy.pi/2, -sympy.pi/4,)), ('U3', (sympy.pi/2, sympy.pi/2, 3*sympy.pi/4,)),),
    "U2_6_m6": (('U2', (3*sympy.pi/4, -3*sympy.pi/4,)), ('U3', (-sympy.pi/2, -sympy.pi/4, sympy.pi/4,)), ('U3', (sympy.pi/2, 3*sympy.pi/4, -3*sympy.pi/4,)),),
    "U2_6_m4": (('U2', (3*sympy.pi/4, -sympy.pi/2,)), ('U3', (-sympy.pi/2, -sympy.pi/4, sympy.pi/2,)), ('U3', (sympy.pi/2, 3*sympy.pi/4, -sympy.pi/2,)),),
    "U2_6_m2": (('U2', (3*sympy.pi/4, -sympy.pi/4,)), ('U3', (-sympy.pi/2, -sympy.pi/4, 3*sympy.pi/4,)), ('U3', (sympy.pi/2, 3*sympy.pi/4, -sympy.pi/4,)),),
    "U2_6_0": (('U2', (3*sympy.pi/4, 0,)), ('U3', (-sympy.pi/2, -sympy.pi/4, sympy.pi,)), ('U3', (sympy.pi/2, 3*sympy.pi/4, 0,)),),
    "U2_6_2": (('U2', (3*sympy.pi/4, sympy.pi/4,)), ('U3', (-sympy.pi/2, -sympy.pi/4, -3*sympy.pi/4,)), ('U3', (sympy.pi/2, 3*sympy.pi/4, sympy.pi/4,)),),
    "U2_6_4": (('U2', (3*sympy.pi/4, sympy.pi/2,)), ('U3', (-sympy.pi/2, -sympy.pi/4, -sympy.pi/2,)), ('U3', (sympy.pi/2, 3*sympy.pi/4, sympy.pi/2,)),),
    "U2_6_6": (('U2', (3*sympy.pi/4, 3*sympy.pi/4,)), ('U3', (-sympy.pi/2, -sympy.pi/4, -sympy.pi/4,)), ('U3', (sympy.pi/2, 3*sympy.pi/4, 3*sympy.pi/4,)),),
    "U2_6_8": (('U2', (3*sympy.pi/4, sympy.pi,)), ('U3', (-sympy.pi/2, -sympy.pi/4, 0,)), ('U3', (sympy.pi/2, 3*sympy.pi/4, sympy.pi,)),),
    "U2_8_m6": (('U2', (sympy.pi, -3*sympy.pi/4,)), ('U3', (-sympy.pi/2, 0, sympy.pi/4,)), ('U3', (sympy.pi/2, sympy.pi, -3*sympy.pi/4,)),),
    "U2_8_m2": (('U2', (sympy.pi, -sympy.pi/4,)), ('U3', (-sympy.pi/2, 0, 3*sympy.pi/4,)), ('U3', (sympy.pi/2, sympy.pi, -sympy.pi/4,)),),
    "U2_8_2": (('U2', (sympy.pi, sympy.pi/4,)), ('U3', (-sympy.pi/2, 0, -3*sympy.pi/4,)), ('U3', (sympy.pi/2, sympy.pi, sympy.pi/4,)),),
    "U2_8_6": (('U2', (sympy.pi, 3*sympy.pi/4,)), ('U3', (-sympy.pi/2, 0, -sympy.pi/4,)), ('U3', (sympy.pi/2, sympy.pi, 3*sympy.pi/4,)),),
    "U3_m12_m6_m6": (('U3', (-3*sympy.pi/2, -3*sympy.pi/4, -3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, sympy.pi/4, sympy.pi/4,)),),
    "U3_m12_m6_m4": (('U3', (-3*sympy.pi/2, -3*sympy.pi/4, -sympy.pi/2,)), ('U3', (3*sympy.pi/2, sympy.pi/4, sympy.pi/2,)),),
    "U3_m12_m6_m2": (('U3', (-3*sympy.pi/2, -3*sympy.pi/4, -sympy.pi/4,)), ('U3', (3*sympy.pi/2, sympy.pi/4, 3*sympy.pi/4,)),),
    "U3_m12_m6_0": (('U3', (-3*sympy.pi/2, -3*sympy.pi/4, 0,)), ('U3', (3*sympy.pi/2, sympy.pi/4, sympy.pi,)),),
    "U3_m12_m6_2": (('U3', (-3*sympy.pi/2, -3*sympy.pi/4, sympy.pi/4,)), ('U3', (3*sympy.pi/2, sympy.pi/4, -3*sympy.pi/4,)),),
    "U3_m12_m6_4": (('U3', (-3*sympy.pi/2, -3*sympy.pi/4, sympy.pi/2,)), ('U3', (3*sympy.pi/2, sympy.pi/4, -sympy.pi/2,)),),
    "U3_m12_m6_6": (('U3', (-3*sympy.pi/2, -3*sympy.pi/4, 3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, sympy.pi/4, -sympy.pi/4,)),),
    "U3_m12_m6_8": (('U3', (-3*sympy.pi/2, -3*sympy.pi/4, sympy.pi,)), ('U3', (3*sympy.pi/2, sympy.pi/4, 0,)),),
    "U3_m12_m4_m6": (('U3', (-3*sympy.pi/2, -sympy.pi/2, -3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, sympy.pi/2, sympy.pi/4,)),),
    "U3_m12_m4_m2": (('U3', (-3*sympy.pi/2, -sympy.pi/2, -sympy.pi/4,)), ('U3', (3*sympy.pi/2, sympy.pi/2, 3*sympy.pi/4,)),),
    "U3_m12_m4_2": (('U3', (-3*sympy.pi/2, -sympy.pi/2, sympy.pi/4,)), ('U3', (3*sympy.pi/2, sympy.pi/2, -3*sympy.pi/4,)),),
    "U3_m12_m4_6": (('U3', (-3*sympy.pi/2, -sympy.pi/2, 3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, sympy.pi/2, -sympy.pi/4,)),),
    "U3_m12_m2_m6": (('U3', (-3*sympy.pi/2, -sympy.pi/4, -3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, 3*sympy.pi/4, sympy.pi/4,)),),
    "U3_m12_m2_m4": (('U3', (-3*sympy.pi/2, -sympy.pi/4, -sympy.pi/2,)), ('U3', (3*sympy.pi/2, 3*sympy.pi/4, sympy.pi/2,)),),
    "U3_m12_m2_m2": (('U3', (-3*sympy.pi/2, -sympy.pi/4, -sympy.pi/4,)), ('U3', (3*sympy.pi/2, 3*sympy.pi/4, 3*sympy.pi/4,)),),
    "U3_m12_m2_0": (('U3', (-3*sympy.pi/2, -sympy.pi/4, 0,)), ('U3', (3*sympy.pi/2, 3*sympy.pi/4, sympy.pi,)),),
    "U3_m12_m2_2": (('U3', (-3*sympy.pi/2, -sympy.pi/4, sympy.pi/4,)), ('U3', (3*sympy.pi/2, 3*sympy.pi/4, -3*sympy.pi/4,)),),
    "U3_m12_m2_4": (('U3', (-3*sympy.pi/2, -sympy.pi/4, sympy.pi/2,)), ('U3', (3*sympy.pi/2, 3*sympy.pi/4, -sympy.pi/2,)),),
    "U3_m12_m2_6": (('U3', (-3*sympy.pi/2, -sympy.pi/4, 3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, 3*sympy.pi/4, -sympy.pi/4,)),),
    "U3_m12_m2_8": (('U3', (-3*sympy.pi/2, -sympy.pi/4, sympy.pi,)), ('U3', (3*sympy.pi/2, 3*sympy.pi/4, 0,)),),
    "U3_m12_0_m6": (('U3', (-3*sympy.pi/2, 0, -3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, sympy.pi, sympy.pi/4,)),),
    "U3_m12_0_m2": (('U3', (-3*sympy.pi/2, 0, -sympy.pi/4,)), ('U3', (3*sympy.pi/2, sympy.pi, 3*sympy.pi/4,)),),
    "U3_m12_0_2": (('U3', (-3*sympy.pi/2, 0, sympy.pi/4,)), ('U3', (3*sympy.pi/2, sympy.pi, -3*sympy.pi/4,)),),
    "U3_m12_0_6": (('U3', (-3*sympy.pi/2, 0, 3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, sympy.pi, -sympy.pi/4,)),),
    "U3_m12_2_m6": (('U3', (-3*sympy.pi/2, sympy.pi/4, -3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, -3*sympy.pi/4, sympy.pi/4,)),),
    "U3_m12_2_m4": (('U3', (-3*sympy.pi/2, sympy.pi/4, -sympy.pi/2,)), ('U3', (3*sympy.pi/2, -3*sympy.pi/4, sympy.pi/2,)),),
    "U3_m12_2_m2": (('U3', (-3*sympy.pi/2, sympy.pi/4, -sympy.pi/4,)), ('U3', (3*sympy.pi/2, -3*sympy.pi/4, 3*sympy.pi/4,)),),
    "U3_m12_2_0": (('U3', (-3*sympy.pi/2, sympy.pi/4, 0,)), ('U3', (3*sympy.pi/2, -3*sympy.pi/4, sympy.pi,)),),
    "U3_m12_2_2": (('U3', (-3*sympy.pi/2, sympy.pi/4, sympy.pi/4,)), ('U3', (3*sympy.pi/2, -3*sympy.pi/4, -3*sympy.pi/4,)),),
    "U3_m12_2_4": (('U3', (-3*sympy.pi/2, sympy.pi/4, sympy.pi/2,)), ('U3', (3*sympy.pi/2, -3*sympy.pi/4, -sympy.pi/2,)),),
    "U3_m12_2_6": (('U3', (-3*sympy.pi/2, sympy.pi/4, 3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, -3*sympy.pi/4, -sympy.pi/4,)),),
    "U3_m12_2_8": (('U3', (-3*sympy.pi/2, sympy.pi/4, sympy.pi,)), ('U3', (3*sympy.pi/2, -3*sympy.pi/4, 0,)),),
    "U3_m12_4_m6": (('U3', (-3*sympy.pi/2, sympy.pi/2, -3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, -sympy.pi/2, sympy.pi/4,)),),
    "U3_m12_4_m2": (('U3', (-3*sympy.pi/2, sympy.pi/2, -sympy.pi/4,)), ('U3', (3*sympy.pi/2, -sympy.pi/2, 3*sympy.pi/4,)),),
    "U3_m12_4_2": (('U3', (-3*sympy.pi/2, sympy.pi/2, sympy.pi/4,)), ('U3', (3*sympy.pi/2, -sympy.pi/2, -3*sympy.pi/4,)),),
    "U3_m12_4_6": (('U3', (-3*sympy.pi/2, sympy.pi/2, 3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, -sympy.pi/2, -sympy.pi/4,)),),
    "U3_m12_6_m6": (('U3', (-3*sympy.pi/2, 3*sympy.pi/4, -3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, -sympy.pi/4, sympy.pi/4,)),),
    "U3_m12_6_m4": (('U3', (-3*sympy.pi/2, 3*sympy.pi/4, -sympy.pi/2,)), ('U3', (3*sympy.pi/2, -sympy.pi/4, sympy.pi/2,)),),
    "U3_m12_6_m2": (('U3', (-3*sympy.pi/2, 3*sympy.pi/4, -sympy.pi/4,)), ('U3', (3*sympy.pi/2, -sympy.pi/4, 3*sympy.pi/4,)),),
    "U3_m12_6_0": (('U3', (-3*sympy.pi/2, 3*sympy.pi/4, 0,)), ('U3', (3*sympy.pi/2, -sympy.pi/4, sympy.pi,)),),
    "U3_m12_6_2": (('U3', (-3*sympy.pi/2, 3*sympy.pi/4, sympy.pi/4,)), ('U3', (3*sympy.pi/2, -sympy.pi/4, -3*sympy.pi/4,)),),
    "U3_m12_6_4": (('U3', (-3*sympy.pi/2, 3*sympy.pi/4, sympy.pi/2,)), ('U3', (3*sympy.pi/2, -sympy.pi/4, -sympy.pi/2,)),),
    "U3_m12_6_6": (('U3', (-3*sympy.pi/2, 3*sympy.pi/4, 3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, -sympy.pi/4, -sympy.pi/4,)),),
    "U3_m12_6_8": (('U3', (-3*sympy.pi/2, 3*sympy.pi/4, sympy.pi,)), ('U3', (3*sympy.pi/2, -sympy.pi/4, 0,)),),
    "U3_m12_8_m6": (('U3', (-3*sympy.pi/2, sympy.pi, -3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, 0, sympy.pi/4,)),),
    "U3_m12_8_m2": (('U3', (-3*sympy.pi/2, sympy.pi, -sympy.pi/4,)), ('U3', (3*sympy.pi/2, 0, 3*sympy.pi/4,)),),
    "U3_m12_8_2": (('U3', (-3*sympy.pi/2, sympy.pi, sympy.pi/4,)), ('U3', (3*sympy.pi/2, 0, -3*sympy.pi/4,)),),
    "U3_m12_8_6": (('U3', (-3*sympy.pi/2, sympy.pi, 3*sympy.pi/4,)), ('U3', (3*sympy.pi/2, 0, -sympy.pi/4,)),),
    "U3_m8_m6_m4": (('U3', (-sympy.pi, -3*sympy.pi/4, -sympy.pi/2,)), ('U3', (sympy.pi, sympy.pi/4, sympy.pi/2,)),),
    "U3_m8_m6_0": (('U3', (-sympy.pi, -3*sympy.pi/4, 0,)), ('U3', (sympy.pi, sympy.pi/4, sympy.pi,)),),
    "U3_m8_m6_4": (('U3', (-sympy.pi, -3*sympy.pi/4, sympy.pi/2,)), ('U3', (sympy.pi, sympy.pi/4, -sympy.pi/2,)),),
    "U3_m8_m6_8": (('U3', (-sympy.pi, -3*sympy.pi/4, sympy.pi,)), ('U3', (sympy.pi, sympy.pi/4, 0,)),),
    "U3_m8_m4_m6": (('U3', (-sympy.pi, -sympy.pi/2, -3*sympy.pi/4,)), ('U3', (sympy.pi, sympy.pi/2, sympy.pi/4,)),),
    "U3_m8_m4_m2": (('U3', (-sympy.pi, -sympy.pi/2, -sympy.pi/4,)), ('U3', (sympy.pi, sympy.pi/2, 3*sympy.pi/4,)),),
    "U3_m8_m4_2": (('U3', (-sympy.pi, -sympy.pi/2, sympy.pi/4,)), ('U3', (sympy.pi, sympy.pi/2, -3*sympy.pi/4,)),),
    "U3_m8_m4_6": (('U3', (-sympy.pi, -sympy.pi/2, 3*sympy.pi/4,)), ('U3', (sympy.pi, sympy.pi/2, -sympy.pi/4,)),),
    "U3_m8_m2_m4": (('U3', (-sympy.pi, -sympy.pi/4, -sympy.pi/2,)), ('U3', (sympy.pi, 3*sympy.pi/4, sympy.pi/2,)),),
    "U3_m8_m2_0": (('U3', (-sympy.pi, -sympy.pi/4, 0,)), ('U3', (sympy.pi, 3*sympy.pi/4, sympy.pi,)),),
    "U3_m8_m2_4": (('U3', (-sympy.pi, -sympy.pi/4, sympy.pi/2,)), ('U3', (sympy.pi, 3*sympy.pi/4, -sympy.pi/2,)),),
    "U3_m8_m2_8": (('U3', (-sympy.pi, -sympy.pi/4, sympy.pi,)), ('U3', (sympy.pi, 3*sympy.pi/4, 0,)),),
    "U3_m8_0_m6": (('U3', (-sympy.pi, 0, -3*sympy.pi/4,)), ('U3', (sympy.pi, sympy.pi, sympy.pi/4,)),),
    "U3_m8_0_m2": (('U3', (-sympy.pi, 0, -sympy.pi/4,)), ('U3', (sympy.pi, sympy.pi, 3*sympy.pi/4,)),),
    "U3_m8_0_2": (('U3', (-sympy.pi, 0, sympy.pi/4,)), ('U3', (sympy.pi, sympy.pi, -3*sympy.pi/4,)),),
    "U3_m8_0_6": (('U3', (-sympy.pi, 0, 3*sympy.pi/4,)), ('U3', (sympy.pi, sympy.pi, -sympy.pi/4,)),),
    "U3_m8_2_m4": (('U3', (-sympy.pi, sympy.pi/4, -sympy.pi/2,)), ('U3', (sympy.pi, -3*sympy.pi/4, sympy.pi/2,)),),
    "U3_m8_2_0": (('U3', (-sympy.pi, sympy.pi/4, 0,)), ('U3', (sympy.pi, -3*sympy.pi/4, sympy.pi,)),),
    "U3_m8_2_4": (('U3', (-sympy.pi, sympy.pi/4, sympy.pi/2,)), ('U3', (sympy.pi, -3*sympy.pi/4, -sympy.pi/2,)),),
    "U3_m8_2_8": (('U3', (-sympy.pi, sympy.pi/4, sympy.pi,)), ('U3', (sympy.pi, -3*sympy.pi/4, 0,)),),
    "U3_m8_4_m6": (('U3', (-sympy.pi, sympy.pi/2, -3*sympy.pi/4,)), ('U3', (sympy.pi, -sympy.pi/2, sympy.pi/4,)),),
    "U3_m8_4_m2": (('U3', (-sympy.pi, sympy.pi/2, -sympy.pi/4,)), ('U3', (sympy.pi, -sympy.pi/2, 3*sympy.pi/4,)),),
    "U3_m8_4_2": (('U3', (-sympy.pi, sympy.pi/2, sympy.pi/4,)), ('U3', (sympy.pi, -sympy.pi/2, -3*sympy.pi/4,)),),
    "U3_m8_4_6": (('U3', (-sympy.pi, sympy.pi/2, 3*sympy.pi/4,)), ('U3', (sympy.pi, -sympy.pi/2, -sympy.pi/4,)),),
    "U3_m8_6_m4": (('U3', (-sympy.pi, 3*sympy.pi/4, -sympy.pi/2,)), ('U3', (sympy.pi, -sympy.pi/4, sympy.pi/2,)),),
    "U3_m8_6_0": (('U3', (-sympy.pi, 3*sympy.pi/4, 0,)), ('U3', (sympy.pi, -sympy.pi/4, sympy.pi,)),),
    "U3_m8_6_4": (('U3', (-sympy.pi, 3*sympy.pi/4, sympy.pi/2,)), ('U3', (sympy.pi, -sympy.pi/4, -sympy.pi/2,)),),
    "U3_m8_6_8": (('U3', (-sympy.pi, 3*sympy.pi/4, sympy.pi,)), ('U3', (sympy.pi, -sympy.pi/4, 0,)),),
    "U3_m8_8_m6": (('U3', (-sympy.pi, sympy.pi, -3*sympy.pi/4,)), ('U3', (sympy.pi, 0, sympy.pi/4,)),),
    "U3_m8_8_m2": (('U3', (-sympy.pi, sympy.pi, -sympy.pi/4,)), ('U3', (sympy.pi, 0, 3*sympy.pi/4,)),),
    "U3_m8_8_2": (('U3', (-sympy.pi, sympy.pi, sympy.pi/4,)), ('U3', (sympy.pi, 0, -3*sympy.pi/4,)),),
    "U3_m8_8_6": (('U3', (-sympy.pi, sympy.pi, 3*sympy.pi/4,)), ('U3', (sympy.pi, 0, -sympy.pi/4,)),),
    "U3_16_m6_m4": (('U3', (2*sympy.pi, -3*sympy.pi/4, -sympy.pi/2,)), ('U3', (2*sympy.pi, -sympy.pi/2, -3*sympy.pi/4,)), ('U3', (2*sympy.pi, -sympy.pi/4, sympy.pi,)), ('U3', (2*sympy.pi, 0, 3*sympy.pi/4,)), ('U3', (2*sympy.pi, sympy.pi/4, sympy.pi/2,)), ('U3', (2*sympy.pi, sympy.pi/2, sympy.pi/4,)), ('U3', (2*sympy.pi, 3*sympy.pi/4, 0,)), ('U3', (2*sympy.pi, sympy.pi, -sympy.pi/4,)),),
    "U3_16_m6_0": (('U3', (2*sympy.pi, -3*sympy.pi/4, 0,)), ('U3', (2*sympy.pi, -sympy.pi/2, -sympy.pi/4,)), ('U3', (2*sympy.pi, -sympy.pi/4, -sympy.pi/2,)), ('U3', (2*sympy.pi, 0, -3*sympy.pi/4,)), ('U3', (2*sympy.pi, sympy.pi/4, sympy.pi,)), ('U3', (2*sympy.pi, sympy.pi/2, 3*sympy.pi/4,)), ('U3', (2*sympy.pi, 3*sympy.pi/4, sympy.pi/2,)), ('U3', (2*sympy.pi, sympy.pi, sympy.pi/4,)),),
    "U3_16_m6_4": (('U3', (2*sympy.pi, -3*sympy.pi/4, sympy.pi/2,)), ('U3', (2*sympy.pi, -sympy.pi/2, sympy.pi/4,)), ('U3', (2*sympy.pi, -sympy.pi/4, 0,)), ('U3', (2*sympy.pi, 0, -sympy.pi/4,)), ('U3', (2*sympy.pi, sympy.pi/4, -sympy.pi/2,)), ('U3', (2*sympy.pi, sympy.pi/2, -3*sympy.pi/4,)), ('U3', (2*sympy.pi, 3*sympy.pi/4, sympy.pi,)), ('U3', (2*sympy.pi, sympy.pi, 3*sympy.pi/4,)),),
    "U3_16_m6_8": (('U3', (2*sympy.pi, -3*sympy.pi/4, sympy.pi,)), ('U3', (2*sympy.pi, -sympy.pi/2, 3*sympy.pi/4,)), ('U3', (2*sympy.pi, -sympy.pi/4, sympy.pi/2,)), ('U3', (2*sympy.pi, 0, sympy.pi/4,)), ('U3', (2*sympy.pi, sympy.pi/4, 0,)), ('U3', (2*sympy.pi, sympy.pi/2, -sympy.pi/4,)), ('U3', (2*sympy.pi, 3*sympy.pi/4, -sympy.pi/2,)), ('U3', (2*sympy.pi, sympy.pi, -3*sympy.pi/4,)),),
}
