"""Phase 3 noisy planner and partition descriptors (public API re-exports)."""

from __future__ import annotations

from squander.partitioning.noisy_descriptor import (
    NoisyDescriptorValidationError,
    build_descriptor_audit_record,
    build_partition_descriptor_set,
    build_phase3_continuity_partition_descriptor_set,
    descriptor_member_to_dict,
    descriptor_partition_to_dict,
    preflight_descriptor_request,
    validate_partition_descriptor_set,
    validate_partition_descriptor_set_against_surface,
)
from squander.partitioning.noisy_planner_surface_builders import (
    NoisyPlannerValidationError,
    build_bridge_overlap_report,
    build_canonical_planner_surface_from_bridge_metadata,
    build_canonical_planner_surface_from_legacy_circuit,
    build_canonical_planner_surface_from_operation_specs,
    build_canonical_planner_surface_from_qgd_circuit,
    build_phase3_continuity_planner_surface,
    build_planner_audit_record,
    preflight_planner_request,
)
from squander.partitioning.noisy_types import (
    DEFAULT_PARTITION_DESCRIPTOR_MAX_QUBITS,
    PARTITIONED_DENSITY_MODE,
    PLANNER_OP_KIND_GATE,
    PLANNER_OP_KIND_NOISE,
    PLANNER_OP_KINDS,
    SUPPORTED_GATE_NAMES,
    SUPPORTED_NOISE_NAMES,
    SUPPORTED_PLANNER_SOURCE_TYPES,
    CanonicalNoisyPlannerOperation,
    CanonicalNoisyPlannerSurface,
    NoisyPartitionDescriptor,
    NoisyPartitionDescriptorMember,
    NoisyPartitionDescriptorSet,
    PlannerOperationKindWire,
)

__all__ = [
    "DEFAULT_PARTITION_DESCRIPTOR_MAX_QUBITS",
    "PARTITIONED_DENSITY_MODE",
    "PLANNER_OP_KINDS",
    "PLANNER_OP_KIND_GATE",
    "PLANNER_OP_KIND_NOISE",
    "SUPPORTED_GATE_NAMES",
    "SUPPORTED_NOISE_NAMES",
    "SUPPORTED_PLANNER_SOURCE_TYPES",
    "CanonicalNoisyPlannerOperation",
    "CanonicalNoisyPlannerSurface",
    "NoisyDescriptorValidationError",
    "NoisyPartitionDescriptor",
    "NoisyPartitionDescriptorMember",
    "NoisyPartitionDescriptorSet",
    "NoisyPlannerValidationError",
    "PlannerOperationKindWire",
    "build_bridge_overlap_report",
    "build_canonical_planner_surface_from_bridge_metadata",
    "build_canonical_planner_surface_from_legacy_circuit",
    "build_canonical_planner_surface_from_operation_specs",
    "build_canonical_planner_surface_from_qgd_circuit",
    "build_descriptor_audit_record",
    "build_partition_descriptor_set",
    "build_phase3_continuity_partition_descriptor_set",
    "build_phase3_continuity_planner_surface",
    "build_planner_audit_record",
    "descriptor_member_to_dict",
    "descriptor_partition_to_dict",
    "preflight_descriptor_request",
    "preflight_planner_request",
    "validate_partition_descriptor_set",
    "validate_partition_descriptor_set_against_surface",
]
